## Obtaining the Efficient Frontier - Part II

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Ok, let’s continue the exercise from the last lecture.

You already downloaded the data and generated two random weightings. 

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt
%matplotlib inline

assets = ['WMT', 'FB']
pf_data = pd.read_csv('Walmart_FB_2014_2017.csv', index_col='Date')

pf_data

WMT          FB
Date                             
2013-12-31  71.126411   54.650002
2014-01-02  71.325287   54.709999
2014-01-03  71.090279   54.560001
2014-01-06  70.692558   57.200001
2014-01-07  70.909485   57.919998
...               ...         ...
2017-04-03  70.906502  142.279999
2017-04-04  71.084190  141.729996
2017-04-05  70.728821  141.850006
2017-04-06  70.511650  141.169998
2017-04-07  71.962746  140.779999

[824 rows x 2 columns]

In [3]:
log_returns = np.log(pf_data / pf_data.shift(1))

num_assets = len(assets)

weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.42150484, 0.57849516])

Now, estimate the expected Portfolio Return, Variance, and Volatility.

Expected Portfolio Return:

In [5]:
np.sum(weights * log_returns.mean()) * 250

0.16777881716053855

Expected Portfolio Variance:

In [6]:
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

0.03758940646150751

In [7]:
log_returns.cov()

WMT        FB
WMT  0.000126  0.000035
FB   0.000035  0.000331

In [8]:
weights

array([0.42150484, 0.57849516])

In [9]:
weights.T

array([0.42150484, 0.57849516])

In [10]:
a = np.dot(log_returns.cov() * 250, weights)
a

array([0.01837319, 0.05159078])

In [11]:
np.dot (weights, a)

0.03758940646150751

Expected Portfolio Volatility:

In [12]:
np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights)))

0.19387987637067317

***

The rest of this exercise will be a reproduction of what we did in the previous video.

1)	Create two empty lists. Name them pf_returns and pf_volatilites.

In [13]:
pfolio_returns = []
pfolio_volatilities = []

2)	Create a loop with 1,000 iterations that will generate random weights, summing to 1, and will append the obtained values for the portfolio returns and the portfolio volatilities to pf_returns and pf_volatilities, respectively.

In [14]:
for x in range (1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pfolio_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pfolio_volatilities.append(np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights))))
    
pfolio_returns, pfolio_volatilities

([0.18525011515120102,
  0.14601860627498536,
  0.18418006121867933,
  0.09661140386655585,
  0.24385688471850817,
  0.01580203751244888,
  0.14547742651738244,
  0.21788140306872425,
  0.24916620592969246,
  0.1878752306448335,
  0.15535616762637044,
  0.10352164194777068,
  0.019566486482012996,
  0.28131111554650645,
  0.19693200311996378,
  0.21255382535152464,
  0.2132824546094164,
  0.03458836247315169,
  0.09051783383226339,
  0.15816766424970216,
  0.08191546198617276,
  0.11175305814937511,
  0.03612720074016927,
  0.16533428357442356,
  0.19530557095225373,
  0.09386898454796533,
  0.1978073114065522,
  0.0069734083089677615,
  0.15754128761255132,
  0.16936701475745808,
  0.2676738674774851,
  0.20155502399728734,
  0.14677242596441945,
  0.14439296504650176,
  0.08756676727368443,
  0.11900244281663776,
  0.08928492686506305,
  0.12192894584152422,
  0.08131770433997665,
  0.25663228908087493,
  0.0038631661034444925,
  0.17543642692720351,
  0.20086558043478406,
  0.173199

3)	Transform the obtained lists into NumPy arrays and reassign them to pf_returns and pf_volatilites. Once you have done that, the two objects will be NumPy arrays. 

In [15]:
pfolio_returns = np.array(pfolio_returns)
pfolio_volatilities = np.array(pfolio_volatilities)

pfolio_returns, pfolio_volatilities

(array([0.18525012, 0.14601861, 0.18418006, 0.0966114 , 0.24385688,
        0.01580204, 0.14547743, 0.2178814 , 0.24916621, 0.18787523,
        0.15535617, 0.10352164, 0.01956649, 0.28131112, 0.196932  ,
        0.21255383, 0.21328245, 0.03458836, 0.09051783, 0.15816766,
        0.08191546, 0.11175306, 0.0361272 , 0.16533428, 0.19530557,
        0.09386898, 0.19780731, 0.00697341, 0.15754129, 0.16936701,
        0.26767387, 0.20155502, 0.14677243, 0.14439297, 0.08756677,
        0.11900244, 0.08928493, 0.12192895, 0.0813177 , 0.25663229,
        0.00386317, 0.17543643, 0.20086558, 0.17319933, 0.16486977,
        0.0913156 , 0.2788846 , 0.07037711, 0.16393794, 0.23745634,
        0.03373104, 0.14787616, 0.08931042, 0.05903527, 0.19352799,
        0.22466043, 0.09246097, 0.05812998, 0.13985545, 0.27620996,
        0.16216327, 0.0954815 , 0.24675342, 0.10049388, 0.14616061,
        0.07231859, 0.14193491, 0.15563235, 0.04292649, 0.20381971,
        0.10026699, 0.16548943, 0.13544489, 0.20