## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [13]:
import numpy as np

a = np.array([[0, 1.0, 2.0, 3, 4, 5],[6, 7, 8, 9.0, 10.0, 11],[1212.0, 13, 14, 15 ,16, 17.0]])

a

array([[0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00],
       [6.000e+00, 7.000e+00, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01],
       [1.212e+03, 1.300e+01, 1.400e+01, 1.500e+01, 1.600e+01, 1.700e+01]])

Check the dimension you have created is correct (use “*.shape*”)

In [15]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [18]:
a[1,4]= 19.75
a

array([[0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00],
       [6.000e+00, 7.000e+00, 8.000e+00, 9.000e+00, 1.975e+01, 1.100e+01],
       [1.212e+03, 1.300e+01, 1.400e+01, 1.500e+01, 1.600e+01, 1.700e+01]])

Extract the 2nd and the 3rd row of the array you created. 

In [19]:
a[1]

array([ 6.  ,  7.  ,  8.  ,  9.  , 19.75, 11.  ])

In [20]:
a[2]

array([1212.,   13.,   14.,   15.,   16.,   17.])