## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

data = pd.read_csv('MSFT_2000.csv', index_col = 'Date')

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([-3.42521946e-05])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([0.01939682])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [7]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [14]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[1.00042963, 0.99320675, 0.97344304, ..., 0.99702615, 1.00905517,
        1.00035023],
       [0.98703327, 0.99326787, 1.00324322, ..., 0.96929209, 0.96515642,
        0.9645651 ],
       [1.01243641, 1.00231301, 1.0030922 , ..., 1.01385702, 0.97373992,
        0.9859709 ],
       ...,
       [0.99215895, 1.01827641, 0.96013466, ..., 0.99734099, 1.00488907,
        1.01249483],
       [1.00595816, 1.00671237, 0.99857937, ..., 1.03108508, 0.98859976,
        0.99715078],
       [0.98850522, 0.9713219 , 1.02800108, ..., 0.97410887, 0.99073239,
        0.99500042]])